### ISSUE TITLE
Couldn't Find any licensing Details

### ISSUE THREAD

**Issue by sheafferusa** [kshyju/ProjectPlanningTool#3]
Hello, 
Under what license is the source code available??

**Comment by kshyju** [comment]
@sheafferusa Feel free to fork/contribute.

**Comment by ctolkien** [comment]
@kshyju  - unless a license is explicitly defined, this will make people wary of contributing.

**Comment by GeorgeHahn** [comment]
+1, this could be fun to hack on if it had a license.

**Comment by ctolkien** [comment]
Looks to be under Apache 2 license now? Can we close this issue?

**Comment by kshyju** [comment]
Closing as there is a license now.
