### ISSUE TITLE
DB backup missing

### ISSUE THREAD

**Issue by raviprajapat** [kshyju/ProjectPlanningTool#4]
I didn't found any DB backup as you mention it is in DBBackup folder.

**Comment by kshyju** [comment]
I am doing a little rewrite (to MVC6 and getting rid of EF) now. I will upload the db back in few days.

**Comment by Dnsaldi** [comment]
still rewriting??

**Comment by kshyju** [comment]
Sorry ! I got busy with some other things ! I will have it ready by this weekend

**Comment by Dnsaldi** [comment]
Thanks heaps!!

**Comment by kshyju** [comment]
@raviprajapat @Dnsaldi Apologies for the delay. I uploaded a db backup which should work. The rewrite & cleanup is still in progress.

**Comment by raviprajapat** [comment]
Thanks @kshyju
