### ISSUE TITLE
unknown keyword platform

### ISSUE THREAD

**Issue by eldhoabe** [kshyju/ProjectPlanningTool#5]
While building the project i have got 

**unknown keyword platform**

I know this is non-issue in the asp,net referred here [asp.net/issues](https://github.com/aspnet/cli-samples/issues/32)

how to fix with respect to our project. I have tried to remove 

`"netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": { "type": "platform", "version": "1.0.0-*" }
      },
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }`

As suggested in the issues of asp.net. 
But still it doesn't build and showing illegal character is there in the project.json of **TeamBins**

_Note I have able to restore DataAccess projects_

**Comment by kshyju** [comment]
Sorry ! I am still in the middle of migrating to dot net core (from RC2 to final now!!!!) . So currently it is broken. I will post a note once it is done.

**Comment by eldhoabe** [comment]
Sure, 

Please let me know if any help that i can do.

What is the advantage of migrating these to Asp.net core apart from hosting this in linux.

**Comment by kshyju** [comment]
The current version should work on dot net core platform. Let me know if you still have an issue.

**Comment by eldhoabe** [comment]
Thanks i will check and get back to you soon. Really appreciate pretty speed update

**Comment by eldhoabe** [comment]
It works thanks

**Comment by kshyju** [comment]
Sweet.
