### ISSUE TITLE
When .vs folder is included in git checkout, the application wont run (missing config file)

### ISSUE THREAD

**Issue by BrandonLegault** [kshyju/ProjectPlanningTool#8]
I forked the project and cloned to my local machine, was able to build etc... but not run the project. I was receiving the following error:
![untitled](https://cloud.githubusercontent.com/assets/10144426/20192645/bf34c770-a758-11e6-9ddd-484ccfc90c02.png)

The project is being made aware of the web.config file in the `.vs\config\applicationhost.config` file, which is user-dependent settings. The file is regenerated with the proper values when the .vs folder is deleted. Adding the .vs folder to .gitignore will solve this problem.

**Comment by kshyju** [comment]
Closing. Thanks
